// GENERATED by tools/gen-kb.mjs from kb/style-library.ttl — do not edit; edit the .ttl then re-run.
// BaziDIY 款式库绑定（只读）。
export const styles: Record<string, unknown> = {
  "styles": {
    "B-01": {
      "name": "素圈单圈手串",
      "positions": [
        {
          "slot": 0,
          "role": "main",
          "variant_filter": [
            "round",
            "buddha",
            "barrel"
          ]
        }
      ],
      "constraints": []
    },
    "B-02": {
      "name": "主珠款单圈手串",
      "positions": [
        {
          "slot": 0,
          "role": "main",
          "min_dia": 10,
          "variant_filter": [
            "round",
            "buddha"
          ]
        },
        {
          "slot": 1,
          "role": "spacer",
          "variant_filter": [
            "spacer"
          ]
        },
        {
          "slot": 2,
          "role": "body",
          "min_dia": 6,
          "max_dia": 8,
          "variant_filter": [
            "round",
            "buddha"
          ]
        },
        {
          "slot": -1,
          "role": "spacer",
          "variant_filter": [
            "spacer"
          ]
        }
      ],
      "constraints": [
        {
          "name": "diameter",
          "type": "diameter",
          "variables": [
            "v0",
            "v2",
            "v1"
          ],
          "params": {
            "main_min": 10,
            "body": [
              6,
              8
            ]
          },
          "reason": "主珠≥10mm,体珠6或8mm"
        },
        {
          "name": "spacer",
          "type": "spacer_map",
          "variables": [
            "v1",
            "v2"
          ],
          "reason": "隔片-体珠映射"
        }
      ]
    },
    "B-03": {
      "name": "隔片款单圈手串",
      "positions": [
        {
          "slot": 0,
          "role": "main",
          "variant_filter": [
            "round",
            "buddha"
          ]
        },
        {
          "slot": 1,
          "role": "main",
          "variant_filter": [
            "round",
            "buddha"
          ]
        },
        {
          "slot": 2,
          "role": "spacer",
          "variant_filter": [
            "spacer"
          ]
        }
      ],
      "constraints": [
        {
          "name": "same_main",
          "type": "same_bead",
          "variables": [
            "v0",
            "v1"
          ],
          "reason": "材质一致"
        }
      ]
    },
    "B-10": {
      "name": "五行拼色单圈手串",
      "positions": [
        {
          "slot": 0,
          "role": "wuxing",
          "variant_filter": [
            "round",
            "buddha"
          ]
        }
      ],
      "constraints": []
    }
  },
  "spacer_diameter_map": {
    "6": 4,
    "8": 4,
    "10": 5,
    "12": 6
  }
}
