// GENERATED by tools/gen-kb.mjs from kb/wuxing-ganzhi.ttl — do not edit; edit the .ttl then re-run.
// BaziDIY 五行·干支·节气 词库绑定（只读）。
export const elementOrder: string[] = ["木","火","土","金","水"]
export const generates: Record<string, string> = {"木":"火","火":"土","土":"金","金":"水","水":"木"}
export const restricts: Record<string, string> = {"木":"土","土":"水","水":"火","火":"金","金":"木"}
export interface Stem { name: string; order: number; element: string }
export interface Branch { name: string; order: number; element: string }
export interface SeasonNode { name: string; month: number; day: number }
export const stems: Stem[] = [{"name":"甲","order":0,"element":"木"},{"name":"乙","order":1,"element":"木"},{"name":"丙","order":2,"element":"火"},{"name":"丁","order":3,"element":"火"},{"name":"戊","order":4,"element":"土"},{"name":"己","order":5,"element":"土"},{"name":"庚","order":6,"element":"金"},{"name":"辛","order":7,"element":"金"},{"name":"壬","order":8,"element":"水"},{"name":"癸","order":9,"element":"水"}]
export const branches: Branch[] = [{"name":"子","order":0,"element":"水"},{"name":"丑","order":1,"element":"土"},{"name":"寅","order":2,"element":"木"},{"name":"卯","order":3,"element":"木"},{"name":"辰","order":4,"element":"土"},{"name":"巳","order":5,"element":"火"},{"name":"午","order":6,"element":"火"},{"name":"未","order":7,"element":"土"},{"name":"申","order":8,"element":"金"},{"name":"酉","order":9,"element":"金"},{"name":"戌","order":10,"element":"土"},{"name":"亥","order":11,"element":"水"}]
export const seasons: SeasonNode[] = [{"name":"立春","month":2,"day":4},{"name":"惊蛰","month":3,"day":6},{"name":"清明","month":4,"day":5},{"name":"立夏","month":5,"day":6},{"name":"芒种","month":6,"day":6},{"name":"小暑","month":7,"day":7},{"name":"立秋","month":8,"day":7},{"name":"白露","month":9,"day":8},{"name":"寒露","month":10,"day":8},{"name":"立冬","month":11,"day":7},{"name":"大雪","month":12,"day":7},{"name":"小寒","month":1,"day":6}]
export const STEM_NAMES: string[] = ["甲","乙","丙","丁","戊","己","庚","辛","壬","癸"]
export const BRANCH_NAMES: string[] = ["子","丑","寅","卯","辰","巳","午","未","申","酉","戌","亥"]
export const STEM_ELEMENT: Record<string, string> = {"甲":"木","乙":"木","丙":"火","丁":"火","戊":"土","己":"土","庚":"金","辛":"金","壬":"水","癸":"水"}
export const BRANCH_ELEMENT: Record<string, string> = {"子":"水","丑":"土","寅":"木","卯":"木","辰":"土","巳":"火","午":"火","未":"土","申":"金","酉":"金","戌":"土","亥":"水"}
