-- GENERATED by tools/export-ossie-seed.mjs from kb binding (parity source).
-- BaziDIY 珠子库 · Ossie 数据层 schema（实例 = 本库；契约见 ../*.yaml）
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS materials (
  id   TEXT PRIMARY KEY,          -- 材料键（唯一）
  name TEXT NOT NULL              -- 材料名（如 白银）
);

CREATE TABLE IF NOT EXISTS variants (
  id   TEXT PRIMARY KEY           -- 变体（round/buddha/barrel/spacer/pixiu）
);

CREATE TABLE IF NOT EXISTS beads (
  id        TEXT PRIMARY KEY,     -- 珠实例唯一标识（材料×变体）
  bead_id   TEXT NOT NULL,        -- 材料键（=materials.id）
  material  TEXT NOT NULL REFERENCES materials(id),
  variant   TEXT NOT NULL REFERENCES variants(id),
  name      TEXT NOT NULL,        -- 展示名（如 南红）
  wuxing    TEXT NOT NULL,        -- 属五行：木/火/土/金/水
  diameters TEXT NOT NULL,        -- JSON 数组，如 [6,8,10,12]
  color     TEXT NOT NULL,        -- 主题色 #RRGGBB
  image     TEXT NOT NULL,        -- 图片地址（相对 /beads）
  image_w   INTEGER NOT NULL,
  image_h   INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_beads_material ON beads(material);
CREATE INDEX IF NOT EXISTS idx_beads_wuxing  ON beads(wuxing);
