-- GENERATED by tools/export-ossie-style.mjs — 款式种子。

INSERT OR REPLACE INTO styles(id, name) VALUES ('B-01', '素圈单圈手串');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-01', 0, 'main', NULL, NULL, '["round","buddha","barrel"]');
INSERT OR REPLACE INTO styles(id, name) VALUES ('B-02', '主珠款单圈手串');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-02', 0, 'main', 10, NULL, '["round","buddha"]');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-02', 1, 'spacer', NULL, NULL, '["spacer"]');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-02', 2, 'body', 6, 8, '["round","buddha"]');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-02', -1, 'spacer', NULL, NULL, '["spacer"]');
INSERT OR REPLACE INTO style_constraints(style_id, name, type, variables, params, reason) VALUES ('B-02', 'diameter', 'diameter', '["v0","v2","v1"]', '{"main_min":10,"body":[6,8]}', '主珠≥10mm,体珠6或8mm');
INSERT OR REPLACE INTO style_constraints(style_id, name, type, variables, params, reason) VALUES ('B-02', 'spacer', 'spacer_map', '["v1","v2"]', NULL, '隔片-体珠映射');
INSERT OR REPLACE INTO styles(id, name) VALUES ('B-03', '隔片款单圈手串');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-03', 0, 'main', NULL, NULL, '["round","buddha"]');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-03', 1, 'main', NULL, NULL, '["round","buddha"]');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-03', 2, 'spacer', NULL, NULL, '["spacer"]');
INSERT OR REPLACE INTO style_constraints(style_id, name, type, variables, params, reason) VALUES ('B-03', 'same_main', 'same_bead', '["v0","v1"]', NULL, '材质一致');
INSERT OR REPLACE INTO styles(id, name) VALUES ('B-10', '五行拼色单圈手串');
INSERT OR REPLACE INTO slots(style_id, slot, role, min_dia, max_dia, allowed_variants) VALUES ('B-10', 0, 'wuxing', NULL, NULL, '["round","buddha"]');
INSERT OR REPLACE INTO spacer_map(body, spacer) VALUES (6, 4);
INSERT OR REPLACE INTO spacer_map(body, spacer) VALUES (8, 4);
INSERT OR REPLACE INTO spacer_map(body, spacer) VALUES (10, 5);
INSERT OR REPLACE INTO spacer_map(body, spacer) VALUES (12, 6);
