// gen-kb.mjs — BaziDIY 款式库生成器（style-library）。
// 珠子库(wuxing/bead)已迁 kb/ossie（Apache Ossie：ontology.yaml + semantic_model + data/*.sql），
// 由 tools/gen-ossie-db.mjs + tools/gen-bindings.mjs 生成（beadCatalog.ts/vocab.ts + ttl 导出）。
// 本脚本只负责款式：kb/style-library.ttl + packages/ontology/src/kb/styleLibrary.ts。
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const KB = join(ROOT, 'kb')
const KB_TS = join(ROOT, 'packages', 'ontology', 'src', 'kb')
mkdirSync(KB, { recursive: true })
mkdirSync(KB_TS, { recursive: true })

const stylesSrc = (await import('file:///' + join(ROOT, 'packages', 'ontology', 'src', 'data', 'styles.ts').replace(/\\/g, '/'))).styles

const esc = (s) => JSON.stringify(String(s))
const w = (lines) => lines.join('\n') + '\n'

function styleTTL() {
  const L = ['@prefix bzd: <https://bazidiy.example/ontology#> .', '', 'bzd:StyleLibraryOntology a owl:Ontology .', '', 'bzd:Style a owl:Class .', 'bzd:config a owl:DatatypeProperty .', '']
  for (const [id, cfg] of Object.entries(stylesSrc.styles)) {
    L.push(`bzd:${id} a bzd:Style .`)
    const payload = { name: cfg.name, positions: cfg.positions, constraints: cfg.constraints }
    L.push(`bzd:${id} bzd:config ${esc(JSON.stringify(payload))} .`)
    L.push('')
  }
  L.push('bzd:spacerMap a owl:Class .')
  for (const [bd, sd] of Object.entries(stylesSrc.spacer_diameter_map)) {
    L.push(`bzd:spacerMap${bd} a bzd:spacerMap .`)
    L.push(`bzd:spacerMap${bd} bzd:body ${bd} .`)
    L.push(`bzd:spacerMap${bd} bzd:spacer ${sd} .`)
  }
  return w(L)
}

function tsStyles() {
  return [
    '// GENERATED by tools/gen-kb.mjs from kb/style-library.ttl — do not edit; edit the .ttl then re-run.',
    '// BaziDIY 款式库绑定（只读）。',
    'export const styles: Record<string, unknown> = ' + JSON.stringify(stylesSrc, null, 2),
    '',
  ].join('\n')
}

writeFileSync(join(KB, 'style-library.ttl'), styleTTL(), 'utf8')
writeFileSync(join(KB_TS, 'styleLibrary.ts'), tsStyles(), 'utf8')
console.log('style ttl + styleLibrary.ts written (wuxing/bead 已归 kb/ossie)')
